# Generated by Django 5.0.7 on 2024-09-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textquestioncontainer",
            name="question_container",
        ),
    ]
