# Generated by Django 5.0.7 on 2024-09-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_textquestioncontainer_question_container"),
    ]

    operations = [
        migrations.AddField(
            model_name="textquestioncontainer",
            name="question_container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.questioncontainer",
            ),
        ),
    ]
