# Generated by Django 4.1.5 on 2024-07-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_student_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="student",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
