# Generated by Django 5.0.7 on 2024-09-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_textquestioncontainer_question_container"),
    ]

    operations = [
        migrations.RenameField(
            model_name="textquestion",
            old_name="number_id",
            new_name="question_number_id",
        ),
    ]
