# Generated by Django 5.0.7 on 2024-09-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_coursematerial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursematerial",
            options={"ordering": ["course_material_title"]},
        ),
        migrations.CreateModel(
            name="AssignCourseToCourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.course",
                    ),
                ),
                (
                    "courseMaterial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.coursematerial",
                    ),
                ),
            ],
        ),
    ]
