# Generated by Django 5.0.7 on 2024-09-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_exercise_alter_answer_answer_input_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_enabled",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_enabled",
        ),
    ]
