# Generated by Django 5.0.7 on 2024-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_student_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
