# Generated by Django 5.0.7 on 2024-09-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="difficulty",
            field=models.CharField(default="General", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.CreateModel(
            name="AssignLessonToCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.lesson",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssignCourseToCourseMaterial",
        ),
        migrations.DeleteModel(
            name="CourseMaterial",
        ),
    ]
