# Generated by Django 5.0.7 on 2024-09-13 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_course_is_enabled_remove_student_is_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="dashboard.exercise",
                    ),
                ),
            ],
        ),
    ]
