# Generated by Django 5.0.7 on 2024-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_course_alter_student_options_student_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
