# Generated by Django 5.0.7 on 2024-09-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_exercisequestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisequestionsanswer",
            name="textQuestion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercise_questions",
                to="dashboard.textquestion",
            ),
        ),
    ]
