# Generated by Django 5.0.7 on 2024-09-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_question"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="TextQuestion",
        ),
    ]
