# Generated by Django 5.0.7 on 2024-09-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_exercisequestionsanswer_textquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisequestionsanswer",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
