# Generated by Django 5.0.7 on 2024-09-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_textquestion_textquestioncontainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="textquestion",
            name="text_question_container",
            field=models.ForeignKey(
                default="general",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.textquestioncontainer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="textquestioncontainer",
            name="question_container",
            field=models.ForeignKey(
                default="general",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.questioncontainer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="textquestioncontainer",
            name="description",
            field=models.TextField(),
        ),
    ]
